### PR TITLE
switch to rgbd_launch

### LINKED ISSUE #5: moving launch files for processing nodelets to a driver independent package
@jonbinney @bit-pirate

I have moved launch files to a separate rgbd_launch package. You can use [this](http://farnsworth.csres.utexas.edu/share/rgbd_launch_test.rosinstall) rosinstall file to test the new organization. 

If things look alright to you, I will first release rgbd_launch, and then submit a pull request for openni_launch and freenect_launch once rgbd_launch makes it to shadow-fixed.

Additionally, there are a number of examples in freenect_launch that you can test out. See the documentation for reference: http://ros.org/wiki/freenect_launch

### PR DESCRIPTION
**Pull request by piyushk**
switches openni_launch to the new external rgbd_launch package for Hydro
- Any usage of kinect_frames or other internal files in openni_launch will result in a deprecation notice
- Removes service error message
- Works with setting depth_registration through dynamic_reconfigure
- Allows you to disable launching nodelets for sw or hw registration through command line flags

closes #5, #6, #7

### CODE REVIEW

**Comment by bit-pirate** [comment]
@jonbinney Please wait a second. I have added another PR myself for what I believe is a minor bug in @piyushk 's PR. Should I retarget the PR to the original repo so that you can merge it?

**Comment by bit-pirate** [comment]
This one I am talking about: https://github.com/piyushk/openni_launch/pull/1

**Comment by jonbinney** [comment]
Yeah, could you target that to this repo? I'll wait to release until that is merged in. Thanks!

**Comment by bit-pirate** [comment]
Done: https://github.com/ros-drivers/openni_launch/pull/9

**Pull request merged**
