### PR TITLE
Fix device registered point cloud generation

### PR DESCRIPTION
**Pull request by piyushk**
xyzrgb cloud generation broke https://github.com/ros-drivers/openni_launch/pull/3 when device registration was enabled. This pull request fixes this.

### CODE REVIEW

**Comment by piyushk** [comment]
@bit-pirate @jonbinney

**Comment by bit-pirate** [comment]
Just commented on your commit https://github.com/piyushk/openni_launch/commit/5f2b684f0fe5eac9f661578936fbfa4cd2f7067e.

**Comment by piyushk** [comment]
I have applied https://github.com/ros-drivers/rgbd_launch/commit/06ec21820c81767864cffbfbe265acc8557d5e0b in 
https://github.com/piyushk/openni_launch/commit/cf357ef2f59f922e05207c594a40949885c6932e (and updated this pull request with the same change)

**Comment by bit-pirate** [comment]
I have tested the updated pull request with the Xtion and Kinect and can confirm it's working.

One thing I don't like though is that we have made this complex launcher even more complex ... Maybe we can do a big makeover with your new proposal rgbd_launch, which I haven't inspected yet, but  will do so soon.

**Comment by piyushk** [comment]
@bit-pirate I agree. I will start a discussion on improvements with rgbd_launch.

@jonbinney v1.9.1 might have broken openni_launch for anybody using device registration. Can you test this pull request out? If you think it is ok, then we should release again.

**Comment by jonbinney** [comment]
Works for me. Merging; will release in a moment.

**Comment by jonbinney** [comment]
Released: https://github.com/ros/rosdistro/pull/1607

**Pull request merged**
